@echo off
rem -----------------------------------------------------------------------------
rem Gradle startup script for Windows
rem
rem Generated by the Gradle Wrapper
rem -----------------------------------------------------------------------------
setlocal
set DIRNAME=%~dp0
nset "EXECUTABLE_JAR=%DIRNAME%gradle\wrapper\gradle-wrapper.jar"

nif defined JAVA_HOME (
  set "JAVACMD=%JAVA_HOME%\bin\java.exe"
) else (
  set "JAVACMD=java"
)

nset "CLASSPATH=%EXECUTABLE_JAR%"

n"%JAVACMD%" %GRADLE_OPTS% -cp "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
endlocal
