#!/usr/bin/env sh
#############################################################################
# Gradle startup script for UN*X
#
# Generated by the Gradle Wrapper
#############################################################################
set -e
# Resolve links - $0 may be a softlink
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/"`expr "$link" : '\(.*\)$'`
  fi
done

PRGDIR=`dirname "$PRG"`
EXECUTABLE_JAR="$PRGDIR/gradle/wrapper/gradle-wrapper.jar"

CLASSPATH="$EXECUTABLE_JAR"

if [ -n "$JAVA_HOME" ] ; then
  JAVACMD="$JAVA_HOME/bin/java"
else
  JAVACMD=java
fi

if [ -z "$GRADLE_HOME" ] ; then
  # Default options
  GRADLE_OPTS="-Xmx64m"
fi

exec "${JAVACMD}" $GRADLE_OPTS -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

