server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 5
      min-spare: 5

spring:
  application:
    name: test-spring-boot-app
  
  # H2 Database configuration for in-memory CRUD
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: true
        url: http://otel-collector.observability.svc.cluster.local:4318/v1/metrics
        step: 10s
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}


# Springdoc configuration
springdoc:
  show-actuator: true

# Logging configuration
logging:
  level:
    com.k8sloverskorea.testspringbootapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: logs/test-spring-boot-app.log

# OpenTelemetry exporter (used by custom OpenTelemetryConfig)
otel:
  exporter:
    otlp:
      endpoint: http://otel-collector.observability.svc.cluster.local:4317