apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: test-spring-boot-app-manifests
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/k8s-lovers-korea/test-spring-boot-app-manifests
  ref:
    tag: main  # Matches the tag created by GitHub Actions for main branch
  # Uncomment below if package is private:
  # secretRef:
  #   name: ghcr-credentials
