name: Build and Push to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/blob/main/README.md
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Render manifests with digest
        run: |
          mkdir -p dist/manifests
          cp -r k8s dist/manifests/
          # Substitute image to pinned digest form
          sed -i "s#ghcr.io/k8s-lovers-korea/test-spring-boot-app:latest#ghcr.io/k8s-lovers-korea/test-spring-boot-app@${{ steps.build.outputs.digest }}#g" dist/manifests/k8s/deployment.yaml
          # Pack as tar.gz for Flux OCI
          tar -czf dist/app.tgz -C dist/manifests .

      - name: Install oras
        run: |
          curl -sL https://github.com/oras-project/oras/releases/download/v1.2.0/oras_1.2.0_linux_amd64.tar.gz | sudo tar -C /usr/local/bin -xz oras

      - name: Login GHCR for oras
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | oras login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push manifests as OCI artifact
        env:
          DEST: ghcr.io/${{ github.repository }}-manifests:latest
        run: |
          oras push "$DEST" \
            --artifact-type application/vnd.cncf.flux.config.v1+tar+gzip \
            --annotation "org.opencontainers.image.title=test-spring-boot-app-manifests" \
            --annotation "org.opencontainers.image.description=Kubernetes manifests for test-spring-boot-app (Deployment/Service)" \
            --annotation "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            dist/app.tgz:application/vnd.cncf.flux.config.v1+tar+gzip

