name: Build and Push OCI Image with Kubernetes Manifests

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-tags: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: false
        cache-read-only: ${{ github.event_name == 'pull_request' }}

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build application
      run: ./gradlew bootJar --no-daemon --stacktrace

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,prefix={{branch}}-
          type=ref,event=branch
          type=ref,event=pr  
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

    - name: Build and push Docker image
      id: build
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-and-push-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for manifests
      id: meta-manifests
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-manifests
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,prefix=sha-

    - name: Update image tag in Kubernetes manifests
      run: |
        # Use the exact same image tag that was built in the previous job
        # Extract the first tag from the multi-line tags output
        IMAGE_TAG=$(echo '${{ needs.build-and-push.outputs.image-tags }}' | head -n1)
        echo "Using image tag: ${IMAGE_TAG}"
        
        # Update the deployment manifest with the correct image tag
        sed -i "s|IMAGE_TAG_PLACEHOLDER|${IMAGE_TAG}|g" k8s/deployment.yaml

    - name: Create OCI artifact with Kubernetes manifests
      run: |
        # Install ORAS CLI
        curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
        tar -xzf oras_1.1.0_linux_amd64.tar.gz
        chmod +x oras
        
        # Use consistent tagging strategy for manifests
        # Extract base tag from the built image tag and apply to manifests
        BASE_IMAGE_TAG=$(echo '${{ needs.build-and-push.outputs.image-tags }}' | head -n1)
        MANIFEST_TAG=$(echo "${BASE_IMAGE_TAG}" | sed 's|${{ env.IMAGE_NAME }}|${{ env.IMAGE_NAME }}-manifests|')
        
        echo "Manifest image tag: ${MANIFEST_TAG}"
        
        # Push Kubernetes manifests as OCI artifact
        ./oras push "${MANIFEST_TAG}" \
          k8s/:application/vnd.k8s.yaml \
          --annotation "org.opencontainers.image.title=Kubernetes Manifests for ${{ github.repository }}" \
          --annotation "org.opencontainers.image.description=Kubernetes deployment manifests"